name: s3_storage
description: dart_s3_storage
version: 1.0.7
homepage: https://github.com/halifox/dart_s3_storage
issue_tracker: https://github.com/halifox/dart_s3_storage

environment:
  sdk: 3.6.0

dependencies:
  meta: 1.15.0
  http: 1.2.2
  crypto: 3.0.6
  convert: 3.1.2
  xml: 6.5.0
  buffer: 1.2.3
  intl: 0.20.1
  mime: 2.0.0
  path: 1.9.0

dev_dependencies:
  pedantic: 1.11.1
  test: 1.25.14
  html: 0.15.5
